apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: example-app-production

resources:
  - ../../base
  - namespace.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
- name: example-app
  literals:
    - STAGE="PRODUCTION"

namespace: example-app-production
