apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: example-app
  literals:
    - STAGE="STAGING"

namespace: example-app-staging
